# Basic
title: Daobin's Den
subtitle: 随心随性 靠, 就是想干嘛干嘛
welcome_message: 
description: Hello，我是稻草人 (@daobin), Java / Js 开发者一名, 现居杭州。漫漫修行路, 吾将上下求索
creator: <a href="http://daobin.wang">@daobin</a>

url: "http://daobin.wang"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    # - {title: 关于, description: 稻草人的介绍, url: 'http://about.daobin.wang'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: BeanHaHa
    mail: 253523241@qq.com

# Google Analytics
ga:
     id: UA-91542598-1
     host: auto
