# Basic
title: Daobin's Den
subtitle: 随心随性，大法~
welcome_message: 
description: 嗨，我是稻草人 (@daobin)，一名来自中国的 Java / Js 开发者。现居杭州，就职于 保险师。修行路上，吾将上下求索
creator: <a href="http://daobin.wang">@daobin</a>

url: "http://daobin.wang"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 稻草人的介绍, url: 'http://about.daobin.wang'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: BeanHaHa
    mail: 253523241@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
